export const mockProducts = [
  {
    id: 1,
    title: "2024 new laptop 15.6 inches",
    price: 4999,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 128,
    ratingCount: 128,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "High performance processor",
      "15.6 inch HD display",
      "8GB RAM, 512GB SSD",
      "Long battery life",
    ],
    colors: ["Silver", "Black", "Space Gray"],
    sizes: ["Standard"],
    description:
      "Latest 2024 laptop with powerful performance and sleek design.",
  },
  {
    id: 2,
    title: "wireless bluetooth headphones active noise cancellation",
    price: 899,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 256,
    ratingCount: 256,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Active noise cancellation",
      "High quality stereo sound",
      "20 hours battery life",
      "Comfortable ear cushions",
    ],
    colors: ["Black", "Blue", "White"],
    sizes: ["One Size"],
    description:
      "Premium wireless headphones with active noise cancellation technology.",
  },
  {
    id: 3,
    title: "smart watch sports health monitoring",
    price: 1299,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 89,
    ratingCount: 89,
    delivery: {
      freeDelivery: false,
      nextDayDelivery: true,
    },
    features: [
      "Heart rate monitoring",
      "Sleep tracking",
      "Water resistant",
      "7 days battery life",
    ],
    colors: ["Black", "Silver", "Rose Gold"],
    sizes: ["Small", "Large"],
    description:
      "Advanced smart watch with comprehensive health monitoring features.",
  },
  {
    id: 4,
    title: "mechanical keyboard rgb backlit",
    price: 399,
    rating: 3,
    image: "https://via.placeholder.com/200",
    reviews: 45,
    ratingCount: 45,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "RGB backlit keys",
      "Mechanical switches",
      "Anti-ghosting",
      "Ergonomic design",
    ],
    colors: ["Black", "White"],
    sizes: ["Full Size", "Tenkeyless"],
    description:
      "Professional mechanical keyboard with customizable RGB lighting.",
  },
  {
    id: 5,
    title: "Professional Kitchen Knife Set",
    price: 899,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 342,
    ratingCount: 342,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "High-quality stainless steel",
      "Ergonomic handles",
      "Knife block included",
      "Lifetime warranty",
    ],
    colors: ["Silver", "Black"],
    sizes: ["Standard"],
    description: "Professional 8-piece kitchen knife set for chefs.",
  },
  {
    id: 6,
    title: "Smart Air Fryer",
    price: 599,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 567,
    ratingCount: 567,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Digital display",
      "Multiple cooking modes",
      "Non-stick coating",
      "Easy cleaning",
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["5L", "7L"],
    description: "Smart air fryer with multiple cooking functions.",
  },
  {
    id: 7,
    title: "Professional Fire Extinguisher",
    price: 299,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "ABC fire rating",
      "Easy to use",
      "Wall mount included",
      "5-year warranty",
    ],
    colors: ["Red"],
    sizes: ["2KG", "4KG"],
    description: "Professional fire extinguisher for home and office.",
  },
  {
    id: 8,
    title: "Smart Smoke Detector",
    price: 199,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Wi-Fi connected",
      "Voice alerts",
      "Battery backup",
      "App control",
    ],
    colors: ["White"],
    sizes: ["Standard"],
    description: "Smart smoke detector with app connectivity.",
  },
  {
    id: 9,
    title: "Luxury Designer Handbag",
    price: 12999,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 89,
    ratingCount: 89,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Genuine leather",
      "Signature pattern",
      "Adjustable strap",
      "Authenticity card",
    ],
    colors: ["Brown", "Black", "Beige"],
    sizes: ["Medium", "Large"],
    description: "Luxury designer handbag with premium materials.",
  },
  {
    id: 10,
    title: "Premium Men's Suit",
    price: 3999,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 156,
    ratingCount: 156,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Italian wool",
      "Tailored fit",
      "Dry clean only",
      "Matching vest",
    ],
    colors: ["Navy", "Black", "Gray"],
    sizes: ["S", "M", "L", "XL"],
    description: "Premium men's suit with Italian wool fabric.",
  },
  {
    id: 11,
    title: "Professional Running Shoes",
    price: 899,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 567,
    ratingCount: 567,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Air cushioning",
      "Breathable mesh",
      "Anti-slip sole",
      "Lightweight",
    ],
    colors: ["Black", "White", "Red"],
    sizes: ["38-45"],
    description: "Professional running shoes with advanced cushioning.",
  },
  {
    id: 12,
    title: "Designer Jeans",
    price: 799,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Premium denim",
      "Slim fit",
      "Stretch fabric",
      "Signature details",
    ],
    colors: ["Blue", "Black", "Gray"],
    sizes: ["28-36"],
    description: "Designer jeans with premium denim fabric.",
  },
  {
    id: 13,
    title: "Professional Yoga Mat",
    price: 299,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Non-slip surface",
      "Extra thick",
      "Eco-friendly",
      "Carrying strap",
    ],
    colors: ["Purple", "Blue", "Black"],
    sizes: ["Standard", "Extra Long"],
    description: "Professional yoga mat with non-slip surface.",
  },
  {
    id: 14,
    title: "Educational Building Blocks",
    price: 199,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 456,
    ratingCount: 456,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Safe materials",
      "Educational value",
      "Storage box",
      "Age 3+",
    ],
    colors: ["Multicolor"],
    sizes: ["100 pieces", "200 pieces"],
    description: "Educational building blocks for children.",
  },
  {
    id: 15,
    title: "Baby Stroller",
    price: 1299,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "One-hand fold",
      "All-terrain wheels",
      "Sun canopy",
      "Storage basket",
    ],
    colors: ["Black", "Gray", "Navy"],
    sizes: ["Standard"],
    description: "Premium baby stroller with multiple features.",
  },
  {
    id: 16,
    title: "Smart Coffee Maker",
    price: 699,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "App control",
      "Programmable",
      "Keep warm",
      "Water filter",
    ],
    colors: ["Black", "Silver", "Red"],
    sizes: ["Standard"],
    description: "Smart coffee maker with app connectivity.",
  },
  {
    id: 17,
    title: "Professional Fire Alarm System",
    price: 599,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 178,
    ratingCount: 178,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Multiple sensors",
      "Voice alerts",
      "Battery backup",
      "Easy installation",
    ],
    colors: ["White"],
    sizes: ["Standard"],
    description: "Professional fire alarm system for home.",
  },
  {
    id: 18,
    title: "Premium Wall Paint",
    price: 299,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 567,
    ratingCount: 567,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Low VOC",
      "Washable",
      "Quick dry",
      "Coverage calculator",
    ],
    colors: ["White", "Beige", "Gray"],
    sizes: ["1L", "5L", "10L"],
    description: "Premium wall paint with low VOC formula.",
  },
  {
    id: 19,
    title: "Luxury Watch",
    price: 8999,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 89,
    ratingCount: 89,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Swiss movement",
      "Sapphire crystal",
      "Water resistant",
      "Leather strap",
    ],
    colors: ["Silver", "Gold", "Rose Gold"],
    sizes: ["Standard"],
    description: "Luxury watch with Swiss movement.",
  },
  {
    id: 20,
    title: "Designer T-Shirt",
    price: 399,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Premium cotton",
      "Signature logo",
      "Regular fit",
      "Machine washable",
    ],
    colors: ["White", "Black", "Gray"],
    sizes: ["S", "M", "L", "XL"],
    description: "Designer t-shirt with premium materials.",
  },
  {
    id: 21,
    title: "Professional Basketball",
    price: 199,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Official size",
      "Durable material",
      "Good grip",
      "Air pump included",
    ],
    colors: ["Orange", "Black"],
    sizes: ["Standard"],
    description: "Professional basketball for indoor/outdoor use.",
  },
  {
    id: 22,
    title: "Educational Robot Kit",
    price: 499,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 178,
    ratingCount: 178,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "STEM learning",
      "Programmable",
      "Battery powered",
      "Age 8+",
    ],
    colors: ["Blue", "White"],
    sizes: ["Standard"],
    description: "Educational robot kit for STEM learning.",
  },
  {
    id: 23,
    title: "Baby Monitor",
    price: 399,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 456,
    ratingCount: 456,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Video monitoring",
      "Night vision",
      "Two-way audio",
      "App control",
    ],
    colors: ["White", "Black"],
    sizes: ["Standard"],
    description: "Smart baby monitor with video and audio.",
  },
  {
    id: 24,
    title: "Smart Refrigerator",
    price: 6999,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Smart cooling",
      "Touch display",
      "Energy efficient",
      "Water dispenser",
    ],
    colors: ["Stainless Steel", "Black"],
    sizes: ["Standard"],
    description: "Smart refrigerator with advanced features.",
  },
  {
    id: 25,
    title: "Fire Escape Ladder",
    price: 199,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Easy deployment",
      "Anti-slip rungs",
      "Compact storage",
      "Weight capacity 1000lbs",
    ],
    colors: ["Silver"],
    sizes: ["2-story", "3-story"],
    description: "Emergency fire escape ladder for home safety.",
  },
  {
    id: 26,
    title: "Premium Floor Tiles",
    price: 299,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 567,
    ratingCount: 567,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Porcelain material",
      "Anti-slip",
      "Easy to clean",
      "Water resistant",
    ],
    colors: ["White", "Gray", "Beige"],
    sizes: ["60x60cm", "80x80cm"],
    description: "Premium floor tiles for home renovation.",
  },
  {
    id: 27,
    title: "Luxury Perfume",
    price: 1299,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Long lasting",
      "Elegant packaging",
      "Signature scent",
      "Gift box",
    ],
    colors: ["Gold", "Silver"],
    sizes: ["50ml", "100ml"],
    description: "Luxury perfume with signature scent.",
  },
  {
    id: 28,
    title: "Designer Sweater",
    price: 899,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Cashmere blend",
      "Classic design",
      "Machine washable",
      "Signature logo",
    ],
    colors: ["Navy", "Gray", "Black"],
    sizes: ["S", "M", "L", "XL"],
    description: "Designer sweater with premium materials.",
  },
  {
    id: 29,
    title: "Professional Tennis Racket",
    price: 699,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 178,
    ratingCount: 178,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Carbon fiber",
      "Professional grip",
      "Head cover",
      "String tension tool",
    ],
    colors: ["Black", "Red"],
    sizes: ["Standard"],
    description: "Professional tennis racket for players.",
  },
  {
    id: 30,
    title: "Building Blocks Set",
    price: 299,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 456,
    ratingCount: 456,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Creative building",
      "Storage box",
      "Age 4+",
      "Multiple colors",
    ],
    colors: ["Multicolor"],
    sizes: ["500 pieces"],
    description: "Creative building blocks set for children.",
  },
  {
    id: 31,
    title: "Baby High Chair",
    price: 599,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Adjustable height",
      "Safety harness",
      "Easy to clean",
      "Foldable",
    ],
    colors: ["White", "Gray", "Blue"],
    sizes: ["Standard"],
    description: "Safe and comfortable baby high chair.",
  },
  {
    id: 32,
    title: "Smart Washing Machine",
    price: 3999,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "App control",
      "Energy efficient",
      "Multiple programs",
      "Quick wash",
    ],
    colors: ["White", "Silver"],
    sizes: ["8kg", "10kg"],
    description: "Smart washing machine with app control.",
  },
  {
    id: 33,
    title: "Fire Safety Kit",
    price: 399,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 567,
    ratingCount: 567,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Fire blanket",
      "First aid kit",
      "Emergency light",
      "Safety guide",
    ],
    colors: ["Red"],
    sizes: ["Standard"],
    description: "Complete fire safety kit for home.",
  },
  {
    id: 34,
    title: "Premium Wallpaper",
    price: 199,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Easy to install",
      "Washable",
      "Pattern matching",
      "Eco-friendly",
    ],
    colors: ["Various"],
    sizes: ["10m roll"],
    description: "Premium wallpaper for home decoration.",
  },
  {
    id: 35,
    title: "Luxury Sunglasses",
    price: 1999,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "UV protection",
      "Polarized lenses",
      "Case included",
      "Signature design",
    ],
    colors: ["Black", "Gold", "Silver"],
    sizes: ["Standard"],
    description: "Luxury sunglasses with polarized lenses.",
  },
  {
    id: 36,
    title: "Designer Jacket",
    price: 1299,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 178,
    ratingCount: 178,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Water resistant",
      "Multiple pockets",
      "Adjustable fit",
      "Signature logo",
    ],
    colors: ["Black", "Navy", "Brown"],
    sizes: ["S", "M", "L", "XL"],
    description: "Designer jacket with premium materials.",
  },
  {
    id: 37,
    title: "Professional Golf Set",
    price: 2999,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 456,
    ratingCount: 456,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Complete set",
      "Carrying bag",
      "Professional clubs",
      "Accessories",
    ],
    colors: ["Black", "Silver"],
    sizes: ["Standard"],
    description: "Professional golf set for players.",
  },
  {
    id: 38,
    title: "Educational Science Kit",
    price: 399,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "STEM learning",
      "Safe materials",
      "Instruction guide",
      "Age 6+",
    ],
    colors: ["Multicolor"],
    sizes: ["Standard"],
    description: "Educational science kit for children.",
  },
  {
    id: 39,
    title: "Baby Car Seat",
    price: 899,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 567,
    ratingCount: 567,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Safety certified",
      "Adjustable",
      "Easy installation",
      "Comfortable",
    ],
    colors: ["Black", "Gray", "Blue"],
    sizes: ["0-4 years"],
    description: "Safe and comfortable baby car seat.",
  },
  {
    id: 40,
    title: "Smart Dishwasher",
    price: 2999,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "App control",
      "Energy efficient",
      "Multiple programs",
      "Quick wash",
    ],
    colors: ["White", "Silver"],
    sizes: ["Standard"],
    description: "Smart dishwasher with app control.",
  },
  {
    id: 41,
    title: "Fire Safety Door",
    price: 1999,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Fire resistant",
      "Security lock",
      "Sound proof",
      "Easy installation",
    ],
    colors: ["White", "Brown"],
    sizes: ["Standard"],
    description: "Fire safety door for home security.",
  },
  {
    id: 42,
    title: "Premium Paint Set",
    price: 499,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 178,
    ratingCount: 178,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Multiple colors",
      "Brushes included",
      "Easy to use",
      "Quick dry",
    ],
    colors: ["Various"],
    sizes: ["Standard"],
    description: "Premium paint set for home decoration.",
  },
  {
    id: 43,
    title: "Luxury Watch Box",
    price: 599,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Wooden material",
      "Soft lining",
      "Lock included",
      "Display case",
    ],
    colors: ["Brown", "Black"],
    sizes: ["6 watches", "12 watches"],
    description: "Luxury watch box for collection.",
  },
  {
    id: 44,
    title: "Designer Dress",
    price: 1999,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 456,
    ratingCount: 456,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Premium fabric",
      "Elegant design",
      "Dry clean only",
      "Signature style",
    ],
    colors: ["Black", "Red", "Blue"],
    sizes: ["XS", "S", "M", "L"],
    description: "Designer dress for special occasions.",
  },
  {
    id: 45,
    title: "Professional Yoga Set",
    price: 499,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Mat included",
      "Blocks",
      "Strap",
      "Carrying bag",
    ],
    colors: ["Purple", "Blue"],
    sizes: ["Standard"],
    description: "Complete yoga set for practice.",
  },
  {
    id: 46,
    title: "Educational Puzzle Set",
    price: 299,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 567,
    ratingCount: 567,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Multiple puzzles",
      "Age appropriate",
      "Storage box",
      "Educational value",
    ],
    colors: ["Multicolor"],
    sizes: ["Standard"],
    description: "Educational puzzle set for children.",
  },
  {
    id: 47,
    title: "Baby Food Maker",
    price: 399,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 345,
    ratingCount: 345,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Steam and blend",
      "Easy to clean",
      "BPA free",
      "Recipe book",
    ],
    colors: ["White", "Green"],
    sizes: ["Standard"],
    description: "Baby food maker for homemade meals.",
  },
  {
    id: 48,
    title: "Smart Oven",
    price: 1999,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 234,
    ratingCount: 234,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "App control",
      "Multiple modes",
      "Self-cleaning",
      "Temperature probe",
    ],
    colors: ["Black", "Stainless Steel"],
    sizes: ["Standard"],
    description: "Smart oven with advanced features.",
  },
  {
    id: 49,
    title: "Fire Safety Cabinet",
    price: 899,
    rating: 5,
    image: "https://via.placeholder.com/200",
    reviews: 178,
    ratingCount: 178,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: true,
    },
    features: [
      "Fire resistant",
      "Lock included",
      "Adjustable shelves",
      "Wall mount",
    ],
    colors: ["Gray", "Black"],
    sizes: ["Small", "Large"],
    description: "Fire safety cabinet for documents.",
  },
  {
    id: 50,
    title: "Premium Curtain Set",
    price: 699,
    rating: 4,
    image: "https://via.placeholder.com/200",
    reviews: 456,
    ratingCount: 456,
    delivery: {
      freeDelivery: true,
      nextDayDelivery: false,
    },
    features: [
      "Blackout fabric",
      "Thermal insulation",
      "Easy to install",
      "Machine washable",
    ],
    colors: ["Beige", "Gray", "Blue"],
    sizes: ["Standard"],
    description: "Premium curtain set for home.",
  }
];
